stages:
  build-docker:
    cmd: calkit build-docker rvat-re-dep -i Dockerfile --platform linux/amd64
    deps:
      - Dockerfile
    outs:
      - Dockerfile-lock.json:
          cache: false
          persist: true
    always_changed: true
  plot-perf-curves:
    cmd: calkit runenv -n main python plot.py perf_curves --save --no-show
    deps:
      - plot.py
      - pyrvatrd/plotting.py
      - pyrvatrd/processing.py
      - Data/Processed
      - Dockerfile-lock.json
    outs:
      - Figures/cp_curves.pdf
      - Figures/cd_curves.pdf
  plot-wake-profiles:
    cmd: calkit runenv -n main python plot.py wake_profiles --save --no-show
    deps:
      - plot.py
      - pyrvatrd/plotting.py
      - pyrvatrd/processing.py
      - Data/Processed
      - Dockerfile-lock.json
    outs:
      - Figures/mean_u_k_profiles.pdf
    meta:
      calkit:
        type: figure
        title: Wake profiles
        description: >
          Mean streamwise velocity and turbulence kinetic energy.
  plot-perf-re-dep:
    cmd: calkit runenv -n main python plot.py perf_re_dep --save --no-show
    deps:
      - plot.py
      - pyrvatrd/plotting.py
      - pyrvatrd/processing.py
      - Data/Processed
      - Dockerfile-lock.json
    outs:
      - Figures/perf_re_dep.pdf
    meta:
      calkit:
        type: figure
        title: Turbine performance Reynolds number dependence
        description: >
          Power and drag (or thrust) curves as a function of Reynolds number,
          computed with both the turbine diameter and blade chord length.
